import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowUp } from "lucide-react";
import { useEffect, useState } from "react";
import { setMeta } from "@/lib/seo";
import { useNavigate } from "react-router-dom";

type Block =
  | { kind: "text"; text: string }
  | { kind: "list"; list: string[] }
  | { kind: "acceptanceIntro" }
  | { kind: "privacyNotice" }
  | { kind: "contactCard" };

type Section = {
  id: string;
  title: string;
  body: Block[];
};

const text = (value: string): Block => ({ kind: "text", text: value });
const list = (items: string[]): Block => ({ kind: "list", list: items });

const sections: Section[] = [
  {
    id: "acceptance-of-terms",
    title: "Acceptance of Terms",
    body: [{ kind: "acceptanceIntro" }],
  },
  {
    id: "use-of-judgmentcalc",
    title: "Use of JudgmentCalc",
    body: [
      text("JudgmentCalc is a cloud-based judgment interest calculator and judgment enforcement software designed to help attorneys and law firms manage judgment cases more efficiently."),
      text("You agree to use the platform only for lawful purposes and in accordance with all applicable laws and regulations."),
      text("You agree not to:"),
      list([
        "Use the platform for any illegal or unauthorized purpose.",
        "Attempt to gain unauthorized access to our systems or data.",
        "Copy, modify, distribute, or resell any part of JudgmentCalc without written permission.",
        "Interfere with the security or operation of the platform.",
      ]),
    ],
  },
  {
    id: "user-accounts",
    title: "User Accounts",
    body: [
      text("You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account."),
      text("Please notify us immediately if you believe your account has been accessed without authorization."),
    ],
  },
  {
    id: "free-trial",
    title: "Free Trial",
    body: [
      text("JudgmentCalc offers a free trial that allows users to explore the platform before purchasing a subscription."),
      text("Unless otherwise stated:"),
      list(["No credit card is required to start the free trial.", "Trial access expires automatically at the end of the trial period.", "Trial data may be removed after the applicable retention period."]),
    ],
  },
  {
    id: "subscription-and-payments",
    title: "Subscription & Payments",
    body: [
      text("Paid subscriptions are billed according to the selected pricing plan."),
      text("By subscribing, you authorize JudgmentCalc to process recurring payments until your subscription is cancelled."),
      text("Subscription fees are non-transferable unless otherwise required by law."),
    ],
  },
  {
    id: "cancellation",
    title: "Cancellation",
    body: [
      text("You may cancel your subscription at any time before your next billing cycle."),
      text("Once cancelled, your subscription will remain active until the end of the current billing period unless otherwise stated."),
    ],
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    body: [
      text("All content, software, branding, logos, graphics, text, and other materials available on JudgmentCalc are the property of JudgmentCalc and are protected by applicable intellectual property laws."),
      text("You may not reproduce, distribute, or use our content without prior written permission."),
    ],
  },
  {
    id: "disclaimer",
    title: "Disclaimer",
    body: [
      text("JudgmentCalc is designed to assist attorneys with judgment interest calculations and case management. The software is provided as a productivity tool and does not constitute legal advice."),
      text("Users are responsible for reviewing all calculations, court requirements, and applicable laws before relying on the information generated by the platform."),
    ],
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of Liability",
    body: [
      text("To the maximum extent permitted by law, JudgmentCalc shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use of our website or software."),
      text("Our total liability shall not exceed the amount paid for your subscription, where permitted by applicable law."),
    ],
  },
  {
    id: "privacy",
    title: "Privacy",
    body: [{ kind: "privacyNotice" }],
  },
  {
    id: "changes-to-these-terms",
    title: "Changes to These Terms",
    body: [
      text("We may update these Terms & Conditions from time to time to reflect changes to our services or legal requirements. Updated versions will be published on this page, so please check back periodically to stay informed."),
    ],
  },
  {
    id: "contact-us",
    title: "Contact Us",
    body: [{ kind: "contactCard" }],
  },
];

const TermsAndConditions = () => {
  const navigate = useNavigate();
  const reduceMotion = useReducedMotion();
  const [showBackToTop, setShowBackToTop] = useState(false);

  useEffect(() => {
    setMeta({
      title: "Terms & Conditions | JudgmentCalc",
      description:
        "Read the JudgmentCalc Terms & Conditions to understand our website policies, subscription terms, billing, account responsibilities, and acceptable use of our platform.",
    });

    const handleScroll = () => setShowBackToTop(window.scrollY > 900);
    window.addEventListener("scroll", handleScroll, { passive: true });
    handleScroll();
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const reveal = (delay = 0) => ({
    initial: reduceMotion ? false : { opacity: 0, y: 12 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, amount: 0.2 },
    transition: { duration: 0.45, delay, ease: [0.22, 1, 0.36, 1] as const },
  });

  const linkClass = "text-emerald-700 underline decoration-emerald-300 underline-offset-4 transition-colors hover:text-emerald-900";

  return (
    <main className="bg-white">
      <div className="mx-auto w-full max-w-3xl px-6 py-14 sm:py-20">
        <h1 className="text-center text-3xl leading-tight text-slate-950 sm:text-4xl">
          <span className="font-normal">JudgmentCalc</span> <span className="font-bold">Terms</span>{" "}
          <span className="whitespace-nowrap font-bold">&amp; Conditions</span>
        </h1>

        <div className="mt-10 border-t border-slate-200" />

        <div className="mt-10 space-y-8">
          <p className="text-base leading-8 text-slate-600">
            Welcome to JudgmentCalc. These Terms &amp; Conditions govern your access to and use of our website, software, and related services. By accessing or using JudgmentCalc, you agree to comply with these Terms. If you do not agree with any part of these Terms, please do not use our website or services.
          </p>
          <p className="text-base leading-8 text-slate-600">
            To learn more about our company and the attorney behind JudgmentCalc, please visit our{" "}
            <button type="button" onClick={() => navigate("/about-us")} className={linkClass}>
              About Us
            </button>{" "}
            page.
          </p>

          {sections.map(({ id, title, body }, index) => (
            <motion.section key={id} id={id} {...reveal(Math.min(index * 0.02, 0.1))} className="scroll-mt-8">
              <h2 className="text-base font-bold uppercase tracking-wide text-slate-950">{title}</h2>

              <div className="mt-3 space-y-4">
                {body.map((block, blockIndex) => {
                  switch (block.kind) {
                    case "text":
                      return (
                        <p key={blockIndex} className="text-base leading-8 text-slate-600">
                          {block.text}
                        </p>
                      );

                    case "list":
                      return (
                        <ul key={blockIndex} className="list-disc space-y-1.5 pl-5 text-base leading-7 text-slate-600">
                          {block.list.map((item) => (
                            <li key={item}>{item}</li>
                          ))}
                        </ul>
                      );

                    case "acceptanceIntro":
                      return (
                        <p key={blockIndex} className="text-base leading-8 text-slate-600">
                          By creating an account, starting a free trial, or using any part of JudgmentCalc, you confirm that you have read, understood, and agreed to these Terms &amp; Conditions and our{" "}
                          <button type="button" onClick={() => navigate("/privacy-policy")} className={linkClass}>
                            Privacy Policy
                          </button>
                          .
                        </p>
                      );

                    case "privacyNotice":
                      return (
                        <p key={blockIndex} className="text-base leading-8 text-slate-600">
                          Your privacy is important to us. Please review our{" "}
                          <button type="button" onClick={() => navigate("/privacy-policy")} className={linkClass}>
                            Privacy Policy
                          </button>{" "}
                          to understand how we collect, use, and protect your personal information.
                        </p>
                      );

                    case "contactCard":
                      return (
                        <p key={blockIndex} className="text-base leading-8 text-slate-600">
                          If you have any questions regarding these Terms &amp; Conditions, your subscription, or your account, please visit our{" "}
                          <button type="button" onClick={() => navigate("/contact-us")} className={linkClass}>
                            Contact Us
                          </button>{" "}
                          page. Our team will be happy to assist you.
                        </p>
                      );

                    default:
                      return null;
                  }
                })}
              </div>
            </motion.section>
          ))}

          <p className="text-base leading-8 text-slate-600">
            Thank you for choosing JudgmentCalc. We appreciate the opportunity to support attorneys and law firms with reliable judgment interest calculations and efficient post-judgment case management.
          </p>
        </div>
      </div>

      <AnimatePresence>
        {showBackToTop && (
          <motion.button
            type="button"
            onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
            initial={{ opacity: 0, y: 12, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 12, scale: 0.9 }}
            transition={{ duration: 0.2 }}
            className="fixed bottom-6 right-5 z-40 flex size-12 items-center justify-center rounded-full bg-slate-950 text-white shadow-[0_14px_36px_rgba(15,23,42,0.28)] transition-colors hover:bg-slate-800 sm:bottom-8 sm:right-8"
            aria-label="Back to top"
          >
            <ArrowUp className="size-5" />
          </motion.button>
        )}
      </AnimatePresence>
    </main>
  );
};

export default TermsAndConditions;
